[package]
name = "ontime"
version = "0.1.0"
edition = "2021"
authors = ["João Mello"]
description = "Shows time for selected timezones"

[dependencies]
clap = "4.5.20"
chrono = "0.4.38"
chrono-tz = "0.10.0"
